### ISSUE TITLE
Can it be used on unfinished genomes/scaffolds??

### ISSUE THREAD

**Issue by dheerajdhotre** [fenghen360/HomBlocks#3]
I want to use HomBlocks for 63 chloroplasts genomes but out of these 2 are unfinished genomes with 7 and 9 scaffolds
Shall i put all the scaffolds in one fasta file and try it?

**Comment by BGQ** [comment]
> I want to use HomBlocks for 63 chloroplasts genomes but out of these 2 are unfinished genomes with 7 and 9 scaffolds Shall i put all the scaffolds in one fasta file and try it?

Dear dheerajdhotre,
For unfinished genomes, it is better to paste the fragmented sequences into one seq without considering the order, because the underlying program Mauve will identify collinearity among all genomes. If there is a problem, please contact fenghen360@126.com

**Comment by dheerajdhotre** [comment]
Thanks!
